/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerproducers;

import java.io.FileOutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;

/**
 *
 * @author juanm
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private static final int MAX_AMOUNT = 18;
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startSimulation = new javax.swing.JButton();
        resetValues = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        PlaqueProducerDell = new javax.swing.JTextField();
        RAMProducerDell = new javax.swing.JTextField();
        PowerSupplyProducerDell = new javax.swing.JTextField();
        GraphicsCardProducerDell = new javax.swing.JTextField();
        AssemblerDell = new javax.swing.JTextField();
        CPUProducerDell = new javax.swing.JTextField();
        PlaqueProducerHP = new javax.swing.JTextField();
        RAMProducerHP = new javax.swing.JTextField();
        PowerSupplyProducerHP = new javax.swing.JTextField();
        GraphicsCardProducerHP = new javax.swing.JTextField();
        AssemblerHP = new javax.swing.JTextField();
        CPUProducerHP = new javax.swing.JTextField();
        PlaqueDell = new javax.swing.JTextField();
        RAMDell = new javax.swing.JTextField();
        PowerSupplyDell = new javax.swing.JTextField();
        GraphicsCardDell = new javax.swing.JTextField();
        CPUDell = new javax.swing.JTextField();
        PlaqueCapacityDell = new javax.swing.JTextField();
        RAMCapacityDell = new javax.swing.JTextField();
        PowerSupplyCapacityDell = new javax.swing.JTextField();
        GraphicsCardCapacityDell = new javax.swing.JTextField();
        CPUCapacityDell = new javax.swing.JTextField();
        PlaqueHP = new javax.swing.JTextField();
        RAMHP = new javax.swing.JTextField();
        PowerSupplyHP = new javax.swing.JTextField();
        GraphicsCardHP = new javax.swing.JTextField();
        CPUHP = new javax.swing.JTextField();
        PlaqueCapacityHP = new javax.swing.JTextField();
        RAMCapacityHP = new javax.swing.JTextField();
        PowerSupplyCapacityHP = new javax.swing.JTextField();
        GraphicsCardCapacityHP = new javax.swing.JTextField();
        CPUCapacityHP = new javax.swing.JTextField();
        StandardComputerReadyHP = new javax.swing.JTextField();
        DaysLeft = new javax.swing.JTextField();
        GraphicsCardComputerReadyHP = new javax.swing.JTextField();
        StandardComputerReadyDell = new javax.swing.JTextField();
        GraphicsCardComputerReadyDell = new javax.swing.JTextField();
        DirectorActivity = new javax.swing.JTextField();
        PMFaults = new javax.swing.JTextField();
        PMDiscount = new javax.swing.JTextField();
        PMActivity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PRODUCTORES DE COMPUTADORAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, 30));

        startSimulation.setText("INICIAR SIMULACIÓN");
        startSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimulationActionPerformed(evt);
            }
        });
        getContentPane().add(startSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        resetValues.setText("Colocar nuevos valores");
        resetValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetValuesActionPerformed(evt);
            }
        });
        getContentPane().add(resetValues, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel2.setText("DELL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TARJETAS GRÁFICAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PLACA BASE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CPU");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MEMORIA RAM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 140, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FUENTE DE ALIMENTACIÓN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TARJETAS GRÁFICAS");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 140, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PLACA BASE");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 140, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("CPU");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 140, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("MEMORIA RAM");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 140, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("FUENTE DE ALIMENTACIÓN");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 140, -1));

        jLabel8.setText("MAX");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 30, 20));

        jLabel9.setText("PROJECT MANAGER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 130, 20));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ENSAMBLADORES");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ENSAMBLADORES");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 140, -1));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("TARJETAS GRÁFICAS");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 140, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("PLACA BASE");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 140, -1));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CPU");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 140, -1));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("MEMORIA RAM");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 140, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("FUENTE DE ALIMENTACIÓN");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 140, -1));

        jLabel11.setText("PRODUCTORES");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 100, 20));

        jLabel12.setText("HP");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 100, 20));

        jLabel24.setText("MAX");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 30, 20));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("TARJETAS GRÁFICAS");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 140, -1));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("PLACA BASE");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 140, -1));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("CPU");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 140, -1));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("MEMORIA RAM");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 140, -1));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("FUENTE DE ALIMENTACIÓN");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 140, -1));

        jLabel30.setText("ELEMENTOS");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 100, 20));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("TARJETAS GRÁFICAS");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 140, -1));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("ESTÁNDAR");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 140, -1));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("TARJETAS GRÁFICAS");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 140, -1));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("ESTÁNDAR");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 140, -1));

        jLabel35.setText("DÍAS FALTANTES PARA LA ENTREGA");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 190, 20));

        jLabel36.setText("COMPUTADORAS LISTAS");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 130, 20));

        jLabel37.setText("DIRECTOR");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 130, 20));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("DESCUENTO");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 140, -1));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("ACTIVIDAD");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 140, -1));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("FALTAS");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 140, -1));

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("ACTIVIDAD");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 140, -1));

        PlaqueProducerDell.setEditable(false);
        PlaqueProducerDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlaqueProducerDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaqueProducerDellActionPerformed(evt);
            }
        });
        getContentPane().add(PlaqueProducerDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 30, -1));

        RAMProducerDell.setEditable(false);
        RAMProducerDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAMProducerDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAMProducerDellActionPerformed(evt);
            }
        });
        getContentPane().add(RAMProducerDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 30, -1));

        PowerSupplyProducerDell.setEditable(false);
        PowerSupplyProducerDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PowerSupplyProducerDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerSupplyProducerDellActionPerformed(evt);
            }
        });
        getContentPane().add(PowerSupplyProducerDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 30, -1));

        GraphicsCardProducerDell.setEditable(false);
        GraphicsCardProducerDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GraphicsCardProducerDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsCardProducerDellActionPerformed(evt);
            }
        });
        getContentPane().add(GraphicsCardProducerDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 30, -1));

        AssemblerDell.setEditable(false);
        AssemblerDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AssemblerDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssemblerDellActionPerformed(evt);
            }
        });
        getContentPane().add(AssemblerDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 30, -1));

        CPUProducerDell.setEditable(false);
        CPUProducerDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPUProducerDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUProducerDellActionPerformed(evt);
            }
        });
        getContentPane().add(CPUProducerDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 30, -1));

        PlaqueProducerHP.setEditable(false);
        PlaqueProducerHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlaqueProducerHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaqueProducerHPActionPerformed(evt);
            }
        });
        getContentPane().add(PlaqueProducerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 30, 20));

        RAMProducerHP.setEditable(false);
        RAMProducerHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAMProducerHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAMProducerHPActionPerformed(evt);
            }
        });
        getContentPane().add(RAMProducerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 30, 20));

        PowerSupplyProducerHP.setEditable(false);
        PowerSupplyProducerHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PowerSupplyProducerHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerSupplyProducerHPActionPerformed(evt);
            }
        });
        getContentPane().add(PowerSupplyProducerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 30, 20));

        GraphicsCardProducerHP.setEditable(false);
        GraphicsCardProducerHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GraphicsCardProducerHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsCardProducerHPActionPerformed(evt);
            }
        });
        getContentPane().add(GraphicsCardProducerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 30, 20));

        AssemblerHP.setEditable(false);
        AssemblerHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AssemblerHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssemblerHPActionPerformed(evt);
            }
        });
        getContentPane().add(AssemblerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 30, 20));

        CPUProducerHP.setEditable(false);
        CPUProducerHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPUProducerHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUProducerHPActionPerformed(evt);
            }
        });
        getContentPane().add(CPUProducerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 30, 20));

        PlaqueDell.setEditable(false);
        PlaqueDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlaqueDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaqueDellActionPerformed(evt);
            }
        });
        getContentPane().add(PlaqueDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 30, -1));

        RAMDell.setEditable(false);
        RAMDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAMDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAMDellActionPerformed(evt);
            }
        });
        getContentPane().add(RAMDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 30, -1));

        PowerSupplyDell.setEditable(false);
        PowerSupplyDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PowerSupplyDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerSupplyDellActionPerformed(evt);
            }
        });
        getContentPane().add(PowerSupplyDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 30, -1));

        GraphicsCardDell.setEditable(false);
        GraphicsCardDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GraphicsCardDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsCardDellActionPerformed(evt);
            }
        });
        getContentPane().add(GraphicsCardDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 30, -1));

        CPUDell.setEditable(false);
        CPUDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPUDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUDellActionPerformed(evt);
            }
        });
        getContentPane().add(CPUDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 30, -1));

        PlaqueCapacityDell.setEditable(false);
        PlaqueCapacityDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlaqueCapacityDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaqueCapacityDellActionPerformed(evt);
            }
        });
        getContentPane().add(PlaqueCapacityDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 30, -1));

        RAMCapacityDell.setEditable(false);
        RAMCapacityDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAMCapacityDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAMCapacityDellActionPerformed(evt);
            }
        });
        getContentPane().add(RAMCapacityDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 30, -1));

        PowerSupplyCapacityDell.setEditable(false);
        PowerSupplyCapacityDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PowerSupplyCapacityDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerSupplyCapacityDellActionPerformed(evt);
            }
        });
        getContentPane().add(PowerSupplyCapacityDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 30, -1));

        GraphicsCardCapacityDell.setEditable(false);
        GraphicsCardCapacityDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GraphicsCardCapacityDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsCardCapacityDellActionPerformed(evt);
            }
        });
        getContentPane().add(GraphicsCardCapacityDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 30, -1));

        CPUCapacityDell.setEditable(false);
        CPUCapacityDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPUCapacityDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUCapacityDellActionPerformed(evt);
            }
        });
        getContentPane().add(CPUCapacityDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 30, -1));

        PlaqueHP.setEditable(false);
        PlaqueHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlaqueHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaqueHPActionPerformed(evt);
            }
        });
        getContentPane().add(PlaqueHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 30, -1));

        RAMHP.setEditable(false);
        RAMHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAMHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAMHPActionPerformed(evt);
            }
        });
        getContentPane().add(RAMHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 30, -1));

        PowerSupplyHP.setEditable(false);
        PowerSupplyHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PowerSupplyHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerSupplyHPActionPerformed(evt);
            }
        });
        getContentPane().add(PowerSupplyHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 30, -1));

        GraphicsCardHP.setEditable(false);
        GraphicsCardHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GraphicsCardHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsCardHPActionPerformed(evt);
            }
        });
        getContentPane().add(GraphicsCardHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 30, -1));

        CPUHP.setEditable(false);
        CPUHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPUHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUHPActionPerformed(evt);
            }
        });
        getContentPane().add(CPUHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 30, -1));

        PlaqueCapacityHP.setEditable(false);
        PlaqueCapacityHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PlaqueCapacityHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaqueCapacityHPActionPerformed(evt);
            }
        });
        getContentPane().add(PlaqueCapacityHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 30, -1));

        RAMCapacityHP.setEditable(false);
        RAMCapacityHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAMCapacityHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAMCapacityHPActionPerformed(evt);
            }
        });
        getContentPane().add(RAMCapacityHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 30, -1));

        PowerSupplyCapacityHP.setEditable(false);
        PowerSupplyCapacityHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PowerSupplyCapacityHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerSupplyCapacityHPActionPerformed(evt);
            }
        });
        getContentPane().add(PowerSupplyCapacityHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 30, -1));

        GraphicsCardCapacityHP.setEditable(false);
        GraphicsCardCapacityHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GraphicsCardCapacityHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsCardCapacityHPActionPerformed(evt);
            }
        });
        getContentPane().add(GraphicsCardCapacityHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 30, -1));

        CPUCapacityHP.setEditable(false);
        CPUCapacityHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPUCapacityHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUCapacityHPActionPerformed(evt);
            }
        });
        getContentPane().add(CPUCapacityHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 30, -1));

        StandardComputerReadyHP.setEditable(false);
        StandardComputerReadyHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StandardComputerReadyHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardComputerReadyHPActionPerformed(evt);
            }
        });
        getContentPane().add(StandardComputerReadyHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 30, -1));

        DaysLeft.setEditable(false);
        DaysLeft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DaysLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaysLeftActionPerformed(evt);
            }
        });
        getContentPane().add(DaysLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 50, 40));

        GraphicsCardComputerReadyHP.setEditable(false);
        GraphicsCardComputerReadyHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GraphicsCardComputerReadyHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsCardComputerReadyHPActionPerformed(evt);
            }
        });
        getContentPane().add(GraphicsCardComputerReadyHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 30, -1));

        StandardComputerReadyDell.setEditable(false);
        StandardComputerReadyDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StandardComputerReadyDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardComputerReadyDellActionPerformed(evt);
            }
        });
        getContentPane().add(StandardComputerReadyDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 30, -1));

        GraphicsCardComputerReadyDell.setEditable(false);
        GraphicsCardComputerReadyDell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GraphicsCardComputerReadyDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsCardComputerReadyDellActionPerformed(evt);
            }
        });
        getContentPane().add(GraphicsCardComputerReadyDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 30, -1));

        DirectorActivity.setEditable(false);
        DirectorActivity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DirectorActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectorActivityActionPerformed(evt);
            }
        });
        getContentPane().add(DirectorActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, 30, -1));

        PMFaults.setEditable(false);
        PMFaults.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PMFaults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMFaultsActionPerformed(evt);
            }
        });
        getContentPane().add(PMFaults, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 30, -1));

        PMDiscount.setEditable(false);
        PMDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PMDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMDiscountActionPerformed(evt);
            }
        });
        getContentPane().add(PMDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 30, -1));

        PMActivity.setEditable(false);
        PMActivity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PMActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMActivityActionPerformed(evt);
            }
        });
        getContentPane().add(PMActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSimulationActionPerformed
        // TODO add your handling code here:
        
        //REVISAR LA ASIGNACION DE LOS TIEMPOS DE SLEEP PARA CADA HILO
        initializeDELLWorkers();
        initializeHPWorkers();
        
    }//GEN-LAST:event_startSimulationActionPerformed
    
    private void initializeDELLWorkers(){
        try {
        // Try to parse the input as a double or integer
        int amount_of_plaque_producers = Integer.parseInt(PlaqueProducerDell.getText());
        int amount_of_graphicCard_producers = Integer.parseInt(GraphicsCardProducerDell.getText());
        int amount_of_powerSupply_producers = Integer.parseInt(PowerSupplyProducerDell.getText());
        int amount_of_ram_producers = Integer.parseInt(RAMProducerDell.getText());
        int amount_of_cpu_producers = Integer.parseInt(CPUProducerDell.getText());
        int amount_of_assemblers = Integer.parseInt(AssemblerDell.getText());
        
        int total_workers = amount_of_plaque_producers + amount_of_graphicCard_producers + amount_of_powerSupply_producers + amount_of_ram_producers + amount_of_cpu_producers;
        
        if (amount_of_plaque_producers > 0 && total_workers <= MAX_AMOUNT) {
            for (int i = 0; i < amount_of_plaque_producers; i++) {
                PlaqueProducer worker = new PlaqueProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_graphicCard_producers; i++) {
                GraphicsCardProducer worker = new GraphicsCardProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_powerSupply_producers; i++) {
                PowerSupplyProducer worker = new PowerSupplyProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_ram_producers; i++) {
                RAMProducer worker = new RAMProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_cpu_producers; i++) {
                CPUProducer worker = new CPUProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_assemblers; i++) {
                Assembler worker = new Assembler(50, 2000, 6, 5, 3, 1, 5, 3, 1);
                worker.start();
            }
            
         }else if (amount_of_plaque_producers <= 0){
            JOptionPane.showMessageDialog(rootPane, "ERROR: Debe ingresar un número positivo.");
        }else{
            JOptionPane.showMessageDialog(rootPane, "ERROR: La cantidad de trabajadores ingresados no debe exceder de 18."); 
         }
        
         // If it parses without throwing an exception, it's numeric
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "ERROR: La cantidad de trabajadores debe ser un número entero."); 
    }
    }
    
    private void initializeHPWorkers(){
        try {
        // Try to parse the input as a double or integer
        int amount_of_plaque_producers = Integer.parseInt(PlaqueProducerHP.getText());
        int amount_of_graphicCard_producers = Integer.parseInt(GraphicsCardProducerHP.getText());
        int amount_of_powerSupply_producers = Integer.parseInt(PowerSupplyProducerHP.getText());
        int amount_of_ram_producers = Integer.parseInt(RAMProducerHP.getText());
        int amount_of_cpu_producers = Integer.parseInt(CPUProducerHP.getText());
        int amount_of_assemblers = Integer.parseInt(AssemblerHP.getText());
        
        if (amount_of_plaque_producers > 0) {
            for (int i = 0; i < amount_of_plaque_producers; i++) {
                PlaqueProducer worker = new PlaqueProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_graphicCard_producers; i++) {
                GraphicsCardProducer worker = new GraphicsCardProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_powerSupply_producers; i++) {
                PowerSupplyProducer worker = new PowerSupplyProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_ram_producers; i++) {
                RAMProducer worker = new RAMProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_cpu_producers; i++) {
                CPUProducer worker = new CPUProducer(25, 500);
                worker.start();
            }
            
            for (int i = 0; i < amount_of_assemblers; i++) {
                Assembler worker = new Assembler(50, 2000, 2, 1, 3, 1, 4, 2, 3);
                worker.start();
            }
            
         }else{
            JOptionPane.showMessageDialog(rootPane, "ERROR: Debe ingresar un número positivo.");
        }
        
         // If it parses without throwing an exception, it's numeric
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "ERROR: La cantidad de trabajadores debe ser un número entero."); 
    }
    }
    
    private void resetValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetValuesActionPerformed
        // TODO add your handling code here:
        int inputDuracionDias = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el tiempo que dura un dia en segundos: "));
        int inputCantidadDias = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese la cantidad de dias entre las entregas de las computadoras a las distribuidoras: "));
        
//      Dell
        int inputPlaqueProducersDell = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de placa base de Dell: "));
        int inputCPUProducersDell = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de CPU de Dell: "));
        int inputRAMProducersDell = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de RAM de Dell: "));
        int inputPowerSupplyProducersDell = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de fuentes de alimentacion de Dell: "));
        int inputGaphicsCardProducersDell = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de tarjetas graficas de Dell: "));
        int inputAssemblersDell = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de ensambladores de Dell: "));
        
//      HP
        int inputPlaqueProducersHP = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de placa base de HP: "));
        int inputCPUProducersHP = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de CPU de HP: "));
        int inputRAMProducersHP = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de RAM de HP: "));
        int inputPowerSupplyProducersHP = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de fuentes de alimentacion de HP: "));
        int inputGaphicsCardProducersHP = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de productores de tarjetas graficas de HP: "));
        int inputAssemblersHP = Integer.parseInt(JOptionPane.showInputDialog(null, "Cantidad de ensambladores de HP: "));

        String archivotxt = inputDuracionDias + "//" + inputCantidadDias + "//" + inputPlaqueProducersDell + "," + inputCPUProducersDell + "," + inputRAMProducersDell + "," + inputPowerSupplyProducersDell + "," + inputGaphicsCardProducersDell + "," + inputAssemblersDell + "//" + inputPlaqueProducersHP + "," + inputCPUProducersHP + "," + inputRAMProducersHP + "," + inputPowerSupplyProducersHP + "," + inputGaphicsCardProducersHP + "," + inputAssemblersHP;
        
        try {
            PrintStream out = new PrintStream(new FileOutputStream("archivo.txt"));
            out.print(archivotxt);
        } catch (Exception e) {
            
        }
        
    
    }//GEN-LAST:event_resetValuesActionPerformed

    private void PlaqueProducerDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaqueProducerDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaqueProducerDellActionPerformed

    private void RAMProducerDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAMProducerDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAMProducerDellActionPerformed

    private void PowerSupplyProducerDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerSupplyProducerDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerSupplyProducerDellActionPerformed

    private void GraphicsCardProducerDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsCardProducerDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsCardProducerDellActionPerformed

    private void AssemblerDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssemblerDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssemblerDellActionPerformed

    private void CPUProducerDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUProducerDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPUProducerDellActionPerformed

    private void PlaqueProducerHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaqueProducerHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaqueProducerHPActionPerformed

    private void RAMProducerHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAMProducerHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAMProducerHPActionPerformed

    private void PowerSupplyProducerHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerSupplyProducerHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerSupplyProducerHPActionPerformed

    private void GraphicsCardProducerHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsCardProducerHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsCardProducerHPActionPerformed

    private void AssemblerHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssemblerHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssemblerHPActionPerformed

    private void CPUProducerHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUProducerHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPUProducerHPActionPerformed

    private void PlaqueDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaqueDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaqueDellActionPerformed

    private void RAMDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAMDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAMDellActionPerformed

    private void PowerSupplyDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerSupplyDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerSupplyDellActionPerformed

    private void GraphicsCardDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsCardDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsCardDellActionPerformed

    private void CPUDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPUDellActionPerformed

    private void PlaqueCapacityDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaqueCapacityDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaqueCapacityDellActionPerformed

    private void RAMCapacityDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAMCapacityDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAMCapacityDellActionPerformed

    private void PowerSupplyCapacityDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerSupplyCapacityDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerSupplyCapacityDellActionPerformed

    private void GraphicsCardCapacityDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsCardCapacityDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsCardCapacityDellActionPerformed

    private void CPUCapacityDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUCapacityDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPUCapacityDellActionPerformed

    private void PlaqueHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaqueHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaqueHPActionPerformed

    private void RAMHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAMHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAMHPActionPerformed

    private void PowerSupplyHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerSupplyHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerSupplyHPActionPerformed

    private void GraphicsCardHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsCardHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsCardHPActionPerformed

    private void CPUHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPUHPActionPerformed

    private void PlaqueCapacityHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaqueCapacityHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaqueCapacityHPActionPerformed

    private void RAMCapacityHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAMCapacityHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAMCapacityHPActionPerformed

    private void PowerSupplyCapacityHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerSupplyCapacityHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerSupplyCapacityHPActionPerformed

    private void GraphicsCardCapacityHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsCardCapacityHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsCardCapacityHPActionPerformed

    private void CPUCapacityHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUCapacityHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPUCapacityHPActionPerformed

    private void StandardComputerReadyHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardComputerReadyHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StandardComputerReadyHPActionPerformed

    private void DaysLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaysLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DaysLeftActionPerformed

    private void GraphicsCardComputerReadyHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsCardComputerReadyHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsCardComputerReadyHPActionPerformed

    private void StandardComputerReadyDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardComputerReadyDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StandardComputerReadyDellActionPerformed

    private void GraphicsCardComputerReadyDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsCardComputerReadyDellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsCardComputerReadyDellActionPerformed

    private void DirectorActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectorActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirectorActivityActionPerformed

    private void PMFaultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMFaultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMFaultsActionPerformed

    private void PMDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMDiscountActionPerformed

    private void PMActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMActivityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssemblerDell;
    private javax.swing.JTextField AssemblerHP;
    private javax.swing.JTextField CPUCapacityDell;
    private javax.swing.JTextField CPUCapacityHP;
    private javax.swing.JTextField CPUDell;
    private javax.swing.JTextField CPUHP;
    private javax.swing.JTextField CPUProducerDell;
    private javax.swing.JTextField CPUProducerHP;
    private javax.swing.JTextField DaysLeft;
    private javax.swing.JTextField DirectorActivity;
    private javax.swing.JTextField GraphicsCardCapacityDell;
    private javax.swing.JTextField GraphicsCardCapacityHP;
    private javax.swing.JTextField GraphicsCardComputerReadyDell;
    private javax.swing.JTextField GraphicsCardComputerReadyHP;
    private javax.swing.JTextField GraphicsCardDell;
    private javax.swing.JTextField GraphicsCardHP;
    private javax.swing.JTextField GraphicsCardProducerDell;
    private javax.swing.JTextField GraphicsCardProducerHP;
    private javax.swing.JTextField PMActivity;
    private javax.swing.JTextField PMDiscount;
    private javax.swing.JTextField PMFaults;
    private javax.swing.JTextField PlaqueCapacityDell;
    private javax.swing.JTextField PlaqueCapacityHP;
    private javax.swing.JTextField PlaqueDell;
    private javax.swing.JTextField PlaqueHP;
    private javax.swing.JTextField PlaqueProducerDell;
    private javax.swing.JTextField PlaqueProducerHP;
    private javax.swing.JTextField PowerSupplyCapacityDell;
    private javax.swing.JTextField PowerSupplyCapacityHP;
    private javax.swing.JTextField PowerSupplyDell;
    private javax.swing.JTextField PowerSupplyHP;
    private javax.swing.JTextField PowerSupplyProducerDell;
    private javax.swing.JTextField PowerSupplyProducerHP;
    private javax.swing.JTextField RAMCapacityDell;
    private javax.swing.JTextField RAMCapacityHP;
    private javax.swing.JTextField RAMDell;
    private javax.swing.JTextField RAMHP;
    private javax.swing.JTextField RAMProducerDell;
    private javax.swing.JTextField RAMProducerHP;
    private javax.swing.JTextField StandardComputerReadyDell;
    private javax.swing.JTextField StandardComputerReadyHP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton resetValues;
    private javax.swing.JButton startSimulation;
    // End of variables declaration//GEN-END:variables
}
